### ISSUE TITLE
売上集計　期間別集計を実行できない・集計結果が正常に表示されない・CSVをダウンロードできない

### ISSUE THREAD

**Issue by arisgi** [EC-CUBE/eccube-2_13#135]
## 概要(Overview)
管理画面 売上集計において、

+ PHP7環境
  - 期間別集計を実行しようとするとシステムエラー
  - 商品別集計・年代別集計・職業別集計・会員別集計を実行した際、グラフの表示に不具合
  - 商品別集計・年代別集計・職業別集計・会員別集計を実行し、CSVダウンロードを実行しようとするとシステムエラー
+ PHP5環境
  - 期間別集計・商品別集計・年代別集計・職業別集計・会員別集計を実行し、CSVダウンロードを実行しようとするとシステムエラー
+ 共通
  - monthのデフォルト値がうまく機能していない

## 期待する内容(Expect)  or 要望 (Requirement)
正しく集計し、正常に結果を表示し、CSVをダウンロードできるようにしたい。

## 再現手順(Procedure)
概要を参照してください。

▼PHP7環境: 期間別集計実行時
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function LC_Page_Admin_Total::lfGetWhereMember(), 3 passed in /var/www/html/eccube217/data/class/pages/admin/total/LC_Page_Admin_Total.php on line 686 
and at least 4 expected in /var/www/html/eccube217/data/class/pages/admin/total/LC_Page_Admin_Total.php:489
Stack trace:
#0 /var/www/html/eccube217/data/class/pages/admin/total/LC_Page_Admin_Total.php(686): LC_Page_Admin_Total->lfGetWhereMember('create_date', '2017/1/1', '2017/1/31 23:59...')
#1 /var/www/html/eccube217/data/class/pages/admin/total/LC_Page_Admin_Total.php(136): LC_Page_Admin_Total->lfGetOrderTerm('all', '2017/1/1', '2017/1/31 23:59...')
#2 /var/www/html/eccube217/data/class/pages/admin/total/LC_Page_Admin_Total.php(92): LC_Page_Admin_Total->action()
#3 /var/www/html/eccube217/data/class_extends/page_extends/admin/total/LC_Page_Admin_Total_Ex.php(54): LC_Page_Admin_Total->process()
#4 /var/www/html/eccube217/html/admin/total/index.php(29): LC_Page_Admin_Total_Ex->process()
#5 {main}
  thrown in /var/www/html/eccube217/data/class/pages/admin/total/LC_Page_Admin_Total.php on line 489, 
referer: http://xxx.xxx.xxx.xxx/eccube217/html/admin/total/?page=term
```

▼PHP7環境: 商品別集計・年代別集計・職業別集計・会員別集計のCSVダウンロード実行時
```
PHP Fatal error:  Uncaught  --> Smarty: Unable to load template 'file:main_frame.tpl' <-- 
  thrown in /var/www/html/eccube217/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 185, 
referer: http://xxx.xxx.xxx.xxx/eccube217/html/admin/total/?
```

▼PHP5環境: CSVダウンロード実行時
```
PHP Fatal error:  Uncaught  --> Smarty: Unable to load template 'file:main_frame.tpl' <-- 
  thrown in /var/www/html/eccube217/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 185, 
referer: http://xxx.xxx.xxx.xxx/eccube217/html/admin/total/?
```

### 環境 (environment)

ブランチ：improve/php7

+ PHP7環境
  - PHP: 7.1.8
  - DB: PostgreSQL 9.2.18
+ PHP5環境
  - PHP: 5.4.16
  - DB: MySQL 5.5.58

## 関連情報 (Ref)
#136

**Comment by nobuhiko** [comment]
これですかね
https://github.com/nanasess/ec-cube-extended/pull/45

**Comment by nanasess** [comment]
以下で対応済み
https://github.com/EC-CUBE/eccube-2_13/pull/186
